name: prova_planner
description: Organizador de provas e estudos para estudantes
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  flutter_svg: ^2.0.9
  syncfusion_flutter_calendar: ^31.1.23
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  google_generative_ai: ^0.2.0
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.5.6
  flutter_markdown: ^0.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env # Arquivo de variáveis de ambiente (crie na raiz do projeto)
    - assets/policies/

flutter_launcher_icons:
  android: true
  ios: true
  # image_path: "assets/icon/app_icon.png"  # Descomente e forneça o ícone quando disponível
  # min_sdk_android: 21
  # remove_alpha_ios: true
